w3c/aria-at-automation-harness

src/host/cli-run-plan.js

Prior to this commit, two command-line arguments which were documented
as URLs defaulted to string values that did not describe valid URLs.
Subsequent parsing would produce undesired behavior. For example:
$ node -p 'new URL("localhost:4444").protocol'
localhost:
Specify strings describing URLs for the arguments which are intended to
receive URLs.

fix: correct default values

---

src/host/agent.js

Provide values for non-optional parameters.

fix: forward command-line arguments

---

src/agent/driver-test-runner.js

Prior to this commit, if the Promise stored in the binding named `loaded` rejected while the WebDriver "wait" command was being evaluated, that rejection would trigger a Node.js global "unhandled rejection" error and cause the process to crash.
Track all Promise values so that a rejection in any of them at any time is handled by the caller. Recognize when the expected "load" event has already occurred and stop waiting immediately.
---
@gnarf I've had a change of heart from [my comment yesterday](https://github.com/w3c/aria-at-automation-harness/pull/29#issuecomment-1830865550). Since we are preparing to deploy this for the very first time, there's relatively little risk in changing old code. Now seems like a good opportunity to challenge assumptions because everyone involved expects the …

Handle timeout when waiting for page readiness

---

src/agent/driver-test-runner.js

V2 tests define a `settings` on each command that choses between one of the settings defined for the AT.  Current definitions look something like this (taken from `target.ats` of a combined.json):
```json
"ats": [
{
"key": "jaws",
"settings": "virtualCursor",
"name": "JAWS"
},
{
"key": "jaws",
"settings": "pcCursor",
"name": "JAWS"
},
{
"key": "nvda",
"settings": "browseMode",
"name": "NVDA"
},
{
"key": "nvda",
"settings": "focusMode",
"name": "NVDA"
},
{
"key": "voiceover_macos",
"settings": "defaultMode",
"name": "VoiceOver for macOS"
}
],
```
A command then looks like this:
```json
"commands": [
{
"id": "space",
"keypresses": [
{
"id": "space",
"keystroke": "Space"
}
],
"assertionExceptions": [],
"keystroke": "Space",
"presentationNumber": 1,
"settings": "virtualCursor"
},
```
--- …

support command.settings (mode switch) for v2 tests

---

.gitattributes

Just in case other windows based developers run into the crlf issue later.

Adding eol=lf to .gitattributes for js/json/md files.

---

src/agent/at-driver.js
src/agent/create-test-runner.js

Just trying to be a bit more clear on where the error is happening, both of these errors were thrown deep inside libraries (ws/webdriver) previously, rethrowing from our own code gives us some hope of tracking down where in the repository the error flow happens.

Add specific messages for thrown errors in web-driver and at-driver

---

.github/workflows/node.js.yml
package.json

Version 16 reached end-of-life on 2023-09-11
https://nodejs.org/en/blog/announcements/nodejs16-eol/

Drop support for Node.js version 16

---

.github/workflows/node.js.yml
.gitignore
package-lock.json
package.json

JSDoc is incapable of parsing the more advanced type annotations recognized by the TypeScript compiler. Because there is no audience for the documentation produced by JSDoc (this project is an application, not a library) and because the recently-integrated TypeScript compiler validates the JSDoc-style type annotations much more thoroughly, the JSDoc package itself provides little value. Remove it.

Remove JSDoc

---

src/agent/driver-test-runner.js

I think this might've snuck in with the latest TSC stuff but I ran into an error of "Invalid URL" when trying to run latest main on my machine.
noticed there was a doubled `:` and `/` in the base url here `http:://127.0.0.1:1234//url` is what it looked like

fix a path building issue

---

src/agent/driver-test-runner.js

Have seen errors while trying to switch modes on firefox.  Occasionally it will end up reading out extra information after switching modes, for example `"Focus Mode\n Pizza Crust\n Grouping"`  
Updated the mode switch to check each line of the output individually for the correct mode text.

check each line of messages for the correct mode on mode switch

---

src/agent/driver-test-runner.js

I've structured this as two commits to ease the review process.
[These commands are defined in ARIA-AT.](https://github.com/w3c/aria-at/blob/625a22e13bd117c4bb8f7ecdb5e97454f9e935ac/tests/support.json#L66-L93) That includes the apparent duplication between `quickNavOn`/`quickNavOff` and `arrowQuickKeyNavOn`/`arrowQuickKeyNavOff`. @howard-e and I intend to verify the intention behind that separately.

Add support for modifying VoiceOver settings

---

src/agent/driver-test-runner.js

Without a return here the code path drops through and throws `Unable to ensure proper settings. Unknown atName NVDA`

Fix: NVDA ensureSettings path not throwing unkown atName

---

README.md

Update project description, remove information on the low-level "agent" utility (there are no known use-cases for direct invocation of this tool), remove CLI documentation (this is subject to rot), add instructions on installation and environment configuration, and add a usage example.
/cc @ChrisC

Improve usage documentation

---

src/agent/browser-driver/create-safari-apple-script-driver.js
src/agent/browser-driver/create.js
src/agent/cli.js
src/agent/create-test-runner.js
src/agent/driver-test-runner.js
src/agent/types.js
src/host/agent.js
src/host/cli-run-plan.js
src/shared/times-option.js
src/shared/types.js

Fixes #49 
Posting this up to check on the approach / acceptability from @jugglinmike 
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207029906610730

configurable timeout and delay values

---

src/host/plan-from.js

This is an oversight that I only coincidentally noticed while reviewing an unrelated patch. Until we resolve gh-59, we can't be confident there aren't more mistakes like it. (cc @ChrisC, who can't currently be formally listed as a reviewer.)

Remove unused binding

---

eslint.config.js
package-lock.json
package.json
src/host/plan-object.js
src/runner/driver-test-runner.js

addresses #68 
This PR adds a default eslint config. Unfortunately, two of the main rules that should be followed have to be disabled due to abnormal patterns. 
1. empty-block pattern
[These very _unique_ pieces of code](https://github.com/w3c/aria-at-automation-harness/blob/main/src/shared/tests/job.js#L45-L51) rely on an empty block. Since the collection being iterated on is `AsyncIterable<any>` the most obvious way of avoiding the empty block is not available.
2. no-unused-var
There are multiple points where an unused var is being used to support type inference.
It would be easier to add both of these rules back in after a Typescript conversion. For now, empty blocks and unused vars will at least produce warnings. Other rules from the eslint default config are now being enforced.

Default eslint config

---

src/runner/driver-test-runner.js

adds support in the test harness for the changes in https://github.com/w3c/aria-at/pull/1125. should be backwards compatible with current single setting approach.
if conflicting settings are in the list, whichever one is later in the list will win.
replaces #73

Support space-separated list of AT settings

---

src/runner/driver-test-runner.js
src/runner/tests/driver-test-runner.js

Implements suggested fix for #83 
I still wonder if there's a more durable way to get a report of mode settings from the AT via AT driver, but this should cover any OS/AT version-level changes to the expected responses for now. 
I tested this locally with macOS 15.4.1  but would appreciate if someone could manually test with NVDA! 🙏🏽

converts desired AT setting responses to arrays

---

src/runner/driver-test-runner.js

@jugglinmike This does the "wrong setting first" approach, but without the last commit, it had the "getSettings" approach, so we could revert d6273ad482ae20c2089f326daf3e9e2c5feb8291 later when getSettings support is added to JAWS
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210763607230188

Jaws confirm setting of virtual pc cursor

---

src/runner/driver-test-runner.js

Fixes for the temporary changes now that the new version of JAWS properly encodes and has getSettings
Closes #90 
Closes #91

Jaws revert temp fixes
